apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: grm
  labels:
    app.kubernetes.io/name: grm
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grm
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
