apiVersion: v1
kind: Secret
metadata:
  name: grm-secret
  namespace: grm
  labels:
    app.kubernetes.io/name: grm
    app.kubernetes.io/component: app
type: Opaque
stringData:
  APP_KEY: "base64:c5An6/FbK/jWRnNbHO2hVnFY4AbCxtXPS7ZbWP1IdnA="
  DB_PASSWORD: "devops"
